import {
  AlertTriangle,
  ArrowLeftFromLine,
  ArrowRight,
  ArrowRightFromLine,
  ArrowUp,
  ArrowUpRight,
  Castle,
  ChevronUp,
  CornerDownRight,
  Crosshair,
  Crown,
  Eye,
  Flame,
  Frown,
  GitFork,
  Hourglass,
  Lock,
  Magnet,
  Pin,
  Puzzle,
  Scan,
  Shield,
  ShieldOff,
  SkipForward,
  Slash,
  Target,
  Wind,
  type LucideIcon,
} from 'lucide-react';

const THEME_ICON: Record<string, LucideIcon> = {
  fork: GitFork,
  pin: Pin,
  skewer: ArrowRight,
  discoveredAttack: Eye,
  doubleCheck: Crosshair,
  sacrifice: Flame,
  attraction: Magnet,
  deflection: Wind,
  interference: Slash,
  defensiveMove: Shield,
  hangingPiece: AlertTriangle,
  trappedPiece: Lock,
  xRayAttack: Scan,
  quietMove: Wind,
  intermezzo: CornerDownRight,
  capturingDefender: ShieldOff,
  exposedKing: Eye,
  attackingF2F7: Target,
  kingsideAttack: ArrowRightFromLine,
  queensideAttack: ArrowLeftFromLine,
  zugzwang: Frown,
  advancedPawn: ChevronUp,
  promotion: ArrowUp,
  underPromotion: ArrowUpRight,
  castling: Castle,
  enPassant: SkipForward,

  mate: Crown,
  mateIn1: Crown,
  mateIn2: Crown,
  mateIn3: Crown,
  mateIn4: Crown,
  mateIn5: Crown,
  anastasiaMate: Crown,
  arabianMate: Crown,
  backRankMate: Crown,
  bodenMate: Crown,
  doubleBishopMate: Crown,
  dovetailMate: Crown,
  hookMate: Crown,
  killBoxMate: Crown,
  smotheredMate: Crown,
  vukovicMate: Crown,

  bishopEndgame: Hourglass,
  knightEndgame: Hourglass,
  pawnEndgame: Hourglass,
  queenEndgame: Hourglass,
  queenRookEndgame: Hourglass,
  rookEndgame: Hourglass,
};

export function themeIcon(slug: string): LucideIcon {
  return THEME_ICON[slug] ?? Puzzle;
}
